# Generated by Django 2.2.5 on 2020-04-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0065_auto_20200417_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fi',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ur',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fi',
            field=models.CharField(db_index=True, default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_ur',
            field=models.CharField(db_index=True, default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childern', to='Shop.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shop.Category'),
        ),
    ]
