# Generated by Django 2.2.5 on 2020-04-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200414_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parent',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('الرياض', 'الرياض'), ('الجبيل', 'الجبيل'), ('الطائف', 'الطائف'), ('حايل', 'حايل'), ('جده', 'جده'), ('الدمام', 'الدمام'), ('المدينة المنورة', 'المدينة المنورة'), ('حفر الباطن', 'حفر الباطن'), ('تبوك', 'تبوك'), ('جيزان', 'جيزان'), ('الخرج', 'الخرج'), ('نجران', 'نجران'), ('ابها', 'ابها'), ('مكه', 'مكه'), ('الاحساء', 'الاحساء'), ('القصيم', 'القصيم'), ('بيشه', 'بيشه')], default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('السعودية', 'السعودية')], default='السعودية', max_length=120),
        ),
    ]
